name: brew install
on:
  push:
    branches: master
  pull_request: []
jobs:
  test-bot:
    runs-on: macos-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Run brew install
        run: |
          set -e
          brew update
          brew install Formula/gigalixir.rb
          gigalixir version
          gigalixir help
          # brew update
          # HOMEBREW_TAP_DIR="/usr/local/Homebrew/Library/Taps/gigalixir/homebrew-brew"
          # mkdir -p "$HOMEBREW_TAP_DIR"
          # rm -rf "$HOMEBREW_TAP_DIR"
          # ln -s "$PWD" "$HOMEBREW_TAP_DIR"
          # brew test-bot
