name: brew install
on:
  push:
    branches: master
  pull_request: []
jobs:
  test-bot:
    runs-on: macos-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Run brew update
        run: brew update
      - name: Run brew install
        run: |
          ls -l
          ls -l Formula
          brew install Formula/gigalixir.rb
      - name: Check gigalixir
        run: |
          gigalixir version
          gigalixir help
